using Math3D;
using Math3D.Geometry;
using Physics3D.Bodies;
using Physics3D.Kinematics;
using Physics3D.Materials;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Physics3D.Collisions
{  
    public interface IImpulseEngine
    {
        /// <summary>
        /// Determines the impulse generated by the intersection between two bodies.
        /// The intersection normal should be pointing away from body B and towards body A.
        /// The returned impulse should be enacted on body A and the negation enacted on body B.
        /// The location of the impulse is the location of the intersection in world space.
        /// </summary>
        Vector3 Collide(Contact c);
    }
    
}
